### ISSUE TITLE
More properties for `postcss-ordered-values`

### ISSUE THREAD

**Issue by evilebottnawi** [cssnano/cssnano#756]
Now we have only:
- animation: animation,
- border: border,
- border-top
- border-right
- border-bottom
- border-left
- outline: border,
- box-shadow
- flex-flow
- transition

**Comment by ben-eb** [comment]
Have a look into these properties:

* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-end
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-block-start
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-end
* https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline-start
* https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
* https://developer.mozilla.org/en-US/docs/Web/CSS/column-rule
* https://developer.mozilla.org/en-US/docs/Web/CSS/columns
* https://developer.mozilla.org/en-US/docs/Web/CSS/display
* https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
* https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant
* https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates
* https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian
* https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
* https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow
* https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation
* https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
* https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style
* https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position
* https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Essentially most of the grammar that uses the double pipe combinator (https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax), but some properties that use this combinator have semantic meaning attached to the order; for instance https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order can not be re-ordered.

**Comment by anikethsaha** [comment]
## Tracking

- [ ] border-block  ( #858 ) 
- [ ] border-block-end  ( #858 ) 
- [ ] border-block-start  ( #858 ) 
- [ ] border-inline  ( #858 ) 
- [ ] border-inline-end  ( #858 ) 
- [ ] border-inline-start  ( #858 ) 
- [ ] clip-path
- [ ] column-rule
- [ ] columns
- [ ] display
- [ ] font-synthesis
- [ ] font-variant
- [ ] font-variant-alternates
- [ ] font-variant-east-asian
- [ ] font-variant-ligatures
- [ ] grid-auto-flow
- [ ] hanging-punctuation
- [ ] list-style
- [ ] shape-outside
- [ ] text-decoration
- [ ] text-decoration-line
- [ ] text-decoration-skip
- [ ] text-emphasis
- [ ] text-emphasis-style
- [ ] text-underline-position
- [ ] touch-action
